// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void () {
    // открыть окно браузера по адресу https://www.google.com
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    // набрать в поле поиска "как тестируют в google"
    driver.findElement(By.name("q")).sendKeys("как тестируют в google");
    // нажать кнопку "поиск"
    driver.findElement(By.name("btnK")).click();
    // Проверка перехода на поисковую выдачу через появление поля "Результатов: примерно"
    {
      List<WebElement> elements = driver.findElements(By.id("result-stats"));
      assert(elements.size() > 0);
    }
    // Проверка перехода на поисковую выдачу через Тайтл страницы "как тестируют в google - Поиск в Google"
    assertThat(driver.getTitle(), is("как тестируют в google - Поиск в Google"));
    // Проверяем текст у элемента "Связанные запросы"
    assertThat(driver.findElement(By.cssSelector(".O3JH7 > .mfMhoc")).getText(), is("Связанные запросы"));
    // Закрыть браузерное окно
    driver.close();
  }
  @Test
  public void 2() {
    // открыть окно браузера по адресу https://www.google.com
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    // набрать в поле поиска "как тестируют в google"
    driver.findElement(By.name("q")).sendKeys("как тестируют в google");
    // нажать кнопку "Мне повезет!"
    driver.findElement(By.name("btnI")).click();
    // Закрыть браузерное окно
    driver.close();
  }
}
